Repository openintegrations/openint, pull requests merged in 2025-05, with the labels that each got.

#547 feat(connect): Moving add to a modal
  apps/web/app/connect/AddConnection.client.tsx
  apps/web/app/connect/MyConnections.client.tsx
  apps/web/app/connect/page.client.tsx
  apps/web/app/connect/page.tsx
  apps/web/app/console/(authenticated)/connect/page.client.tsx
  packages/ui-v1/components/Spinner.tsx
  packages/ui-v1/components/index.ts
  packages/ui-v1/domain-components/LinkConnectorModal.tsx
  packages/ui-v1/domain-components/__stories__/LinkConnectorModal.stories.tsx
  packages/ui-v1/domain-components/index.ts
Labels: size:L

#548 oint-1255 connectorconfig-sheet refactor(DisabledField): Enhance layout and sty…
  packages/ui-v1/components/schema-form/fields.tsx
Labels: size:M

#540 OINT-1251: Fix DataTable so pagination and filtering works server side, not client side
  apps/web/app/console/(authenticated)/connections/page.client.tsx
  apps/web/app/console/(authenticated)/connector-config/page.client.tsx
  apps/web/app/console/(authenticated)/customers/page.client.tsx
  apps/web/app/console/(authenticated)/events/page.client.tsx
  packages/api-v1/__generated__/openapi.json
  packages/api-v1/__generated__/openapi.types.d.ts
  packages/api-v1/trpc/routers/connection.spec.ts
  packages/api-v1/trpc/routers/connection.ts
  packages/api-v1/trpc/routers/connectorConfig.spec.ts
  packages/api-v1/trpc/routers/connectorConfig.ts
  packages/api-v1/trpc/routers/customer.spec.ts
  packages/api-v1/trpc/routers/customer.ts
  packages/api-v1/trpc/routers/event.test.ts
  packages/api-v1/trpc/routers/event.ts
  packages/ui-v1/components/DataTable.tsx
  packages/ui-v1/components/SearchInput.tsx
  packages/ui-v1/components/index.ts
  packages/ui-v1/domain-components/tables/CustomerTable.tsx
Labels: size:L

#549 OINT-1233: Improve console navigation loading states and after mutating values refresh data
  apps/web/app/connect/ConnectorConnect.client.tsx
  apps/web/app/console/(authenticated)/connections/page.tsx
  apps/web/app/console/(authenticated)/connector-config/page.tsx
  apps/web/app/console/(authenticated)/customers/page.tsx
  apps/web/app/console/(authenticated)/events/page.tsx
  apps/web/app/console/(authenticated)/settings/page.client.tsx
  packages/ui-v1/components/DataTable.tsx
Labels: size:M

#550 oint-1221: On organization dropdown change bring back refresh page content
  apps/web/lib-client/GlobalCommandBarProvider.tsx
Labels: size:XS

#554 oint-1266: If there are no configured CCFG default credentials default to showing client_id and client_secret. The toggle should not be shown
  apps/web/app/connect/ConnectorConnect.client.tsx
  apps/web/app/connect/MyConnections.client.tsx
  apps/web/app/connect/page.tsx
  packages/api-v1/__generated__/openapi.json
  packages/api-v1/__generated__/openapi.types.d.ts
  packages/api-v1/trpc/routers/connector.models.ts
  packages/ui-v1/components/schema-form/fields.tsx
Labels: size:S

#557 Fix(api): Readding expired_at to connection
  apps/web/app/console/(authenticated)/connections/page.client.tsx
  connectors/cnext/auth-oauth2/createOAuth2ConnectorServer.ts
  packages/api-v1/trpc/routers/connect.spec.ts
Labels: size:M

#558 fix(api): fixing check connection and tightening tests
  connectors/cnext/auth-oauth2/createOAuth2ConnectorServer.ts
  packages/api-v1/trpc/routers/connection.spec.ts
  packages/api-v1/trpc/routers/connection.ts
Labels: size:M

#560 Fix(connect): Trimming scopes to ensure no empty chars in the case of free form user input
  connectors/cnext/auth-oauth2/utils.spec.ts
  connectors/cnext/auth-oauth2/utils.ts
  packages/oauth2/createOAuth2Client.ts
Labels: size:S

#565 oint-1282: Show OAuth reconnect only when ccfg has connections
  apps/web/app/console/(authenticated)/connector-config/ConnectorConfigDetails.tsx
Labels: size:XS

#564 oint-1238: Generalize SecureInput
  apps/web/app/console/(authenticated)/connections/page.client.tsx
  apps/web/app/console/(authenticated)/settings/page.client.tsx
  packages/ui-v1/components/SecureInput.tsx
  packages/ui-v1/components/WebhookInput.tsx
  packages/ui-v1/components/schema-form/fields.tsx
Labels: size:M

#563 oint-1264: feat(layout): Add metadata for OpenInt and Console update …
  apps/web/app/console/layout.tsx
  apps/web/app/layout.tsx
  apps/web/public/_assets/logo-favicon.svg
Labels: size:S

#556 OINT-1175: scopes component
  apps/web/app/console/(authenticated)/connector-config/ConnectorConfigDetails.tsx
  apps/web/app/console/(authenticated)/connector-config/ConnectorConfigSheet.tsx
  packages/ui-v1/components/ConnectorScopes.stories.tsx
  packages/ui-v1/components/ConnectorScopes.tsx
  packages/ui-v1/components/schema-form/fields.tsx
  packages/ui-v1/domain-components/ConnectorConfigForm.tsx
Labels: size:L

#562 oint-1173: Move display name to advanced expand at the bottom of each ccfg and have placeholder be the current connector name pretty printed
  packages/api-v1/trpc/routers/connectorConfig.models.ts
  packages/ui-v1/components/schema-form/fields.tsx
  packages/ui-v1/components/schema-form/fields/AdvancedField.tsx
  packages/ui-v1/domain-components/ConnectorConfigForm.tsx
Labels: size:L
