Repository openintegrations/openint, pull requests merged in 2025-04, with the labels that each got.

#534 fix(connect): adding URL encoded response parsing support
  packages/oauth2/createOAuth2Client.ts
Labels: size:S

#536 OINT-1234: Customers table fixes
  apps/web/app/console/(authenticated)/connections/page.client.tsx
  apps/web/app/console/(authenticated)/customers/page.client.tsx
  packages/ui-v1/components/DataTable.tsx
  packages/ui-v1/domain-components/tables/CustomerTable.tsx
Labels: size:M

#538 chore(oauth): adding required scopes
  connectors/cnext/auth-oauth2/createOAuth2ConnectorServer.ts
  connectors/cnext/auth-oauth2/schemas.ts
  connectors/cnext/auth-oauth2/utils.spec.ts
  connectors/cnext/auth-oauth2/utils.ts
  connectors/cnext/json-defs/hubspot.ts
Labels: size:L
